added AnimeWorld source
SuperMarcus/NineAnimator pull request #283
Opened 2021-09-15 13:01 UTC by Catta1997

#273

2021-09-20 14:54 UTC, SuperMarcus requested changes

2021-09-20 14:54 UTC, SuperMarcus commented on Modules/Sources/NineAnimatorNativeSources/AnimeSources/AnimeWorld/AnimeWorld+Anime.swift
> +                    let regex = try! NSRegularExpression(pattern: "[0-9]{2} [A-Za-z]* [0-9]{4}")
Might want to consider moving the regex initialization to a class variable.

2021-09-20 16:32 UTC, Catta1997 commented on Modules/Sources/NineAnimatorNativeSources/AnimeSources/AnimeWorld/AnimeWorld+Episode.swift
> +                            target: try video.asURL(),
```suggestion
                            target: try URL(protocolRelativeString: video, relativeTo: self.endpointURL).tryUnwrap(),
```
Like this?

2021-09-21 00:55 UTC, SuperMarcus commented on Modules/Sources/NineAnimatorNativeSources/AnimeSources/AnimeWorld/AnimeWorld+Episode.swift
> +                            target: try video.asURL(),
Yep, that looks good. This just ensures that the source is more resilient to website changes (whenever the website decides to fall back to something like relative addresses, which happened a lot previously).

2021-10-30 21:52 UTC, SuperMarcus approved these changes

2021-10-30 21:52 UTC, merged