Fix AnimeSaturn m3u8 episodes
SuperMarcus/NineAnimator pull request #301
Opened 2022-01-28 08:47 UTC by Catta1997

2022-01-28 15:25 UTC, SuperMarcus requested changes

2022-01-28 15:25 UTC, SuperMarcus commented on Modules/Sources/NineAnimatorNativeSources/AnimeSources/AnimeSaturn/AnimeSaturn+Episode.swift
> +                            finalurl = try URL(string: NASourceAnimeSaturn.regex.firstMatch(in: bowl.debugDescription)?.first ?? "").tryUnwrap()
```suggestion
                            finalurl = try URL(string: NASourceAnimeSaturn.regex.firstMatch(in: utf8Text)?.first ?? "").tryUnwrap()
```

Don't use `.debugDescription` to obtain the original html source.

2022-01-30 21:32 UTC, gtqifan approved these changes

2022-01-30 21:34 UTC, SuperMarcus approved these changes

2022-01-30 21:35 UTC, merged